---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: terraria
configMapGenerator:
  - name: tmodloader-config
    envs:
      - env
resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
